apiVersion: v2
name: roboshop
version: 1.0
  
  
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install test ./chart/
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm ls
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm delete test
#
#   Passing Values from Command Line
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install catalogue ./chart/ --set component=catalogue
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install cart ./chart/ --set component=cart
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install user ./chart/ --set component=user

#   Passing Values from files
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install frontend ./chart/ -f frontend.yml
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install catalogue ./chart/ -f catalogue.yml
#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm install user ./chart/ -f user.yml

#  [ centos@workstation ~/18-learn-kubernetes/roboshop/helm ]$ helm upgrade -i user ./chart/ -f user.yml