FROM      dokken/centos-8
ENV       URL=google.com
ADD      mongodb.repo /etc/yum.repos.d/mongodb.repo
#COPY      mongodb.repo /etc/yum.repos.d/mongodb.repo
#ADD      https://raw.githubusercontent.com/raghudevopsb70/roboshop-ansible/main/roles/common/files/mongodb.repo /etc/yum.repos.d/mongodb.repo

# docker build .
# docker run  dokken/centos-8 env

# docker run  ImageID  env

# Override env variable value
# # docker run  -e URL=yahoo.com ImageID  env